# Generated by Django 2.0.9 on 2018-12-18 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='zagolovok')),
                ('body', models.TextField(verbose_name='tekst')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data sozdaniya')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data obnovleniya')),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='avtor')),
            ],
            options={
                'verbose_name': "stat'ya",
                'verbose_name_plural': "stat'ya",
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'vid',
                'verbose_name_plural': 'vid',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='soderzhaniye')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data sozdaniya')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Blog.Article', verbose_name="stat'ya")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='avtor')),
            ],
            options={
                'verbose_name': 'obzor',
                'verbose_name_plural': 'obzor',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='Blog.Category', verbose_name='vid'),
        ),
    ]
